version: '3.6'

services:
  fedora:
    env_file: dev.env
    image: ghcr.io/samvera/fcrepo4:4.7.5
    hostname: fedora-hyrax
    volumes:
       - ./tmp/fedora-dev-data:/data
    ports:
      - 8984:8080
    environment:
      JAVA_OPTIONS: '-Xmx4096m -Xms1024m -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.postgresql.host=pg-fcrepo -Dfcrepo.postgresql.port=5432 -Dfcrepo.postgresql.username=${FEDORA_PG_USER} -Dfcrepo.postgresql.password=${FEDORA_PG_PASSWORD} -Dfcrepo.properties.management=relaxed'
      MODESHAPE_CONFIG: 'classpath:/config/jdbc-postgresql/repository.json'
    networks:
      - fedora
    depends_on:
      - pg-fcrepo
    restart: always
    logging: &logging
      driver: "local"
  pg-fcrepo:
    env_file: dev.env
    image: postgres:15.4
    hostname: pg-fcrepo
    environment:
      - POSTGRES_USER=$FEDORA_PG_USER
      - POSTGRES_PASSWORD=$FEDORA_PG_PASSWORD
      - POSTGRES_DB=$FEDORA_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - fcrepo-dev-db:/var/lib/postgresql/data
    networks:
      - fedora
    restart: always
    logging: 
      <<: *logging
  pg-hyrax:
    env_file: dev.env
    image: postgres:9.5.25-alpine
    hostname: pg-hyrax
    environment:
      - POSTGRES_USER=$HYRAX_DB_USER
      - POSTGRES_PASSWORD=$HYRAX_DB_PASSWORD
      - POSTGRES_DB=$HYRAX_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - hyrax-dev-db:/var/lib/postgresql/data
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  solr:
    env_file: dev.env
    build: 
     context: .
     dockerfile: Dockerfile-solr
    hostname: solr-hyrax
    environment:
      - SOLR_CORE=$SOLR_CORE
    volumes:
      - ./tmp/solr-cores:/opt/solr/server/solr/mycores
    ports:
      - 8983:8983
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  redis:
    env_file: dev.env
    image: 'redis:5-alpine'
    hostname: redis-hyrax
    command: redis-server
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  sidekiq:
    image: scholarspace-app
    build: 
     context: .
    command: bundle exec sidekiq
    depends_on: 
      - redis
    env_file: dev.env
    volumes: 
     - app-hyrax-dev:/opt/scholarspace
    networks:
      - hyrax
      - fedora
    restart: always
    logging: 
      <<: *logging
  app-server:
    image: scholarspace-app
    depends_on: 
      - solr
      - pg-hyrax
      - fedora
    env_file: dev.env
    networks:
      - hyrax
      - fedora
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    volumes:
     - app-hyrax-dev:/opt/scholarspace
    restart: always
    logging: 
      <<: *logging
    command: ["bash", "-l", "docker/scripts/start-dev-app.sh"]
volumes:
  fcrepo-dev-db:
  hyrax-dev-db:
  app-hyrax-dev:
networks:
  hyrax:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hyrax
  fedora:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-fedora

