version: '3.6'

services:
  fedora:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    hostname: fedora-hyrax
    # Use this map to external volume
    volumes:
       - /data/fedora:/data
    ports:
      - 8984:8080
    environment:
      JAVA_OPTIONS: '-Xmx4096m -Xms1024m -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.postgresql.host=pg-fcrepo -Dfcrepo.postgresql.port=5432 -Dfcrepo.postgresql.username=${FEDORA_PG_USER} -Dfcrepo.postgresql.password=${FEDORA_PG_PASSWORD} -Dfcrepo.properties.management=relaxed'
      MODESHAPE_CONFIG: 'classpath:/config/jdbc-postgresql/repository.json'
    networks:
      - fedora
    depends_on:
      - pg-fcrepo
    restart: always
    logging: &logging
      driver: "local"
  pg-fcrepo:
    image: postgres:15.4
    hostname: pg-fcrepo
    environment:
      - POSTGRES_USER=$FEDORA_PG_USER
      - POSTGRES_PASSWORD=$FEDORA_PG_PASSWORD
      - POSTGRES_DB=$FEDORA_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - fedora
    restart: always
    logging: 
      <<: *logging
  pg-hyrax:
    image: postgres:9.5.25-alpine
    hostname: pg-hyrax
    environment:
      - POSTGRES_USER=$HYRAX_DB_USER
      - POSTGRES_PASSWORD=$HYRAX_DB_PASSWORD
      #- POSTGRES_DB=$HYRAX_DB_DEV          # For development
      - POSTGRES_DB=$HYRAX_DB_PROD          # For production
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-hyrax:/var/lib/postgresql/data
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  solr:
    image: ghcr.io/gwu-libraries/scholarspace-hyrax-solr:master
    #build: 
    #  context: .
    #  dockerfile: Dockerfile-solr
    hostname: solr-hyrax
    environment:
      - SOLR_CORE_DEV=$SOLR_CORE_DEV
      - SOLR_CORE_TEST=$SOLR_CORE_TEST
      - SOLR_CORE_PROD=$SOLR_CORE_PROD
    # Use this to map to an external volume/existing Solr core
    volumes:
      - /var/solr/data:/opt/solr/server/solr/mycores
    ports:
      - 8983:8983
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  redis:
    image: 'redis:5-alpine'
    hostname: redis-hyrax
    command: redis-server
    networks:
      - hyrax
    restart: always
    logging: 
      <<: *logging
  sidekiq:
    image: ghcr.io/gwu-libraries/scholarspace-app:master
    #image: scholarspace-app
    #build: 
    #  context: .
    #  args:
    #    - RAILS_ENV
    command: ["bash", "-l", "docker/scripts/scholarspace-setup.sh", "sidekiq"]
    depends_on: 
      - redis
    env_file: .env
    volumes: 
     - /opt/scholarspace/scholarspace-derivatives:/opt/scholarspace/scholarspace-derivatives
     - app-hyrax:/opt/scholarspace          # For production
    # - /opt/scholarspace:/opt/scholarspace # For development
    networks:
      - hyrax
      - fedora
    restart: always
    logging: 
      <<: *logging
  app-server:
    image: ghcr.io/gwu-libraries/scholarspace-app:master
    #image: scholarspace-app
    depends_on: 
      - solr
      - pg-hyrax
      - fedora
    env_file: .env
    networks:
      - hyrax
      - fedora
    ports:
      - 80:80
      - 443:443
    volumes:
     - ${NGINX_CERT_DIR}:/opt/scholarspace/certs
     - ${NGINX_KEY_DIR}:/opt/scholarspace/keys
     - /opt/scholarspace/scholarspace-derivatives:/opt/scholarspace/scholarspace-derivatives
     - app-hyrax:/opt/scholarspace          # For production
    # - /opt/scholarspace:/opt/scholarspace # For development
    restart: always
    logging: 
      <<: *logging
volumes:
  db:
  db-hyrax:
  app-hyrax:
networks:
  hyrax:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hyrax
  fedora:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-fedora

