version: '3.6'

services:
  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    # Use this map to external volume
    volumes:
       - /data/fedora:/data
    ports:
      - 8984:8080
    environment:
      JAVA_OPTIONS: '-Xmx4096m -Xms1024m -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.postgresql.host=postgres-container -Dfcrepo.postgresql.port=5432 -Dfcrepo.postgresql.username=${FEDORA_PG_USER} -Dfcrepo.postgresql.password=${FEDORA_PG_PASSWORD} -Dfcrepo.properties.management=relaxed'
      MODESHAPE_CONFIG: 'classpath:/config/jdbc-postgresql/repository.json'
    networks:
      - hyrax
    restart: always
  pg-fcrepo:
    image: postgres:latest
    hostname: postgres-container
    restart: always
    environment:
      - POSTGRES_USER=$FEDORA_PG_USER
      - POSTGRES_PASSWORD=$FEDORA_PG_PASSWORD
      - POSTGRES_DB=$FEDORA_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hyrax
  pg-hyrax:
    image: postgres:10.22-alpine
    environment:
      - POSTGRES_USER=$HYRAX_PG_USER
      - POSTGRES_PASSWORD=$HYRAX_PG_PASSWORD
      - POSTGRES_DB=$HYRAX_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-hyrax:/var/lib/postgresql/data
    ports:
      - 5432:5432
  solr:
    build: 
      context: .
      dockerfile: Dockerfile-solr
    # Use this to map to an external volume/existing Solr index
    volumes:
      - /var/solr/data:/opt/solr/server/solr/mycores
    ports:
      - 8983:8983
volumes:
  db:
  db-hyrax:
networks:
  hyrax:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hyrax

