name: CD testing

on:
  # allow running action manually
  workflow_dispatch:
  # trigger on pull request to "master" branch
  push:
    branches:
      - master

jobs:
  CD:
    runs-on: ubuntu-latest
    permissions: 
      packages: read
    steps:
    - name: create pem file
      run: | 
        echo $PRIVATE_KEY > private-key.pem
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - name: Login to test server
      run: |
        ssh -i private-key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        cd /opt/scholarspace/scholarspace-hyrax
        whoami
        ls -l