name: CI testing

on:
  workflow_dispatch:
  push:
    branches:
      - ci-testing
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Create env file
      run: |
        touch .env
        cp ./docker/ci.env /.env
    - name: Run docker-compose stack
      run: docker-compose -f docker-compose.yml up -d 
      