name: CI testing

on:
  workflow_dispatch:
  push:
    branches:
      - ci-testing
      - ci-testing-2
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions: 
      packages: read
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - name: Setup scholarspace folder
      run: |
        id $USER
        mkdir -p /opt/scholarspace
        mkdir /opt/scholarspace/certs
        mkdir /opt/scholarspace-tmp
        mkdir /opt/scholarspace-minter
        mkdir /opt/scholarspace/fedora-data
        mkdir /opt/scholarspace/solr-data
        cd /opt/scholarspace
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Create env file
      run: |
        cp docker/ci.env .env
    - name: Try to start solr
      run: |
        docker-compose up solr